https://openflights.org/data.html


1. Airport ID	Unique OpenFlights identifier for this airport.
2. Name	Name of airport. May or may not contain the City name.
3. City	Main city served by airport. May be spelled differently from Name.
4. Country	Country or territory where airport is located. See Countries to cross-reference to ISO 3166-1 codes.
5. IATA	3-letter IATA code. Null if not assigned/unknown.
 ICAO	4-letter ICAO code. Null if not assigned.
6. Latitude	Decimal degrees, usually to six significant digits. Negative is South, positive is North.
7. Longitude	Decimal degrees, usually to six significant digits. Negative is West, positive is East.
8. Altitude	In feet.
9. Timezone	Hours offset from UTC. Fractional hours are expressed as decimals, eg. India is 5.5.
10. DST	Daylight savings time. One of E (Europe), A (US/Canada), S (South America), O (Australia), Z (New Zealand), N (None) or U (Unknown). See also: Help: Time
11. Tz database time zone	Timezone in "tz" (Olson) format, eg. "America/Los_Angeles".
Type	Type of the airport. Value "airport" for air terminals, "station" for train stations, "port" for ferry terminals and "unknown" if not known. In airports.csv, only type=airport is included.
12. Source	Source of this data. "OurAirports" for data sourced from OurAirports, "Legacy" for old data not matched to OurAirports (mostly DAFIF), "User" for unverified user contributions. In airports.csv, only source=OurAirports is included.

In [ ]:
#Os conjuntos de dados InvestmentBankCDE
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat", sep=",", header=None)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.261200,-70.779198,670,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports

In [ ]:
df.sort_values(9)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
1590,1633,João Paulo II Airport,Ponta Delgada,Portugal,PDL,LPPD,37.741199,-25.697901,259,-1,E,Atlantic/Azores,airport,OurAirports
4369,5675,São Filipe Airport,"Sao Filipe, Fogo Island",Cape Verde,SFL,GVSF,14.885000,-24.480000,617,-1,U,Atlantic/Cape_Verde,airport,OurAirports
7488,13412,Semur En Auxois Airfield,Semur en Auxois,France,\N,LFGQ,47.481899,4.344170,1053,-1,E,\N,airport,OurAirports
1591,1634,Pico Airport,Pico,Portugal,PIX,LPPI,38.554298,-28.441299,109,-1,E,Atlantic/Azores,airport,OurAirports
4482,5793,Corvo Airport,Corvo,Portugal,CVU,LPCR,39.671501,-31.113600,0,-1,E,Atlantic/Azores,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7277,12040,Tumut Airport,NaN,Australia,TUM,YTMU,-35.262798,148.240997,878,\N,\N,\N,airport,OurAirports
7278,12041,Wangaratta Airport,NaN,Australia,WGT,YWGT,-36.415798,146.307007,504,\N,\N,\N,airport,OurAirports
7279,12042,Warracknabeal Airport,NaN,Australia,WKB,YWKB,-36.321098,142.419006,397,\N,\N,\N,airport,OurAirports
7281,12044,West Sale Airport,Sale,Australia,SXE,YWSL,-38.090827,146.965335,72,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports

In [ ]:
df.loc[(df[3]== 'Brazil')&(df[2].str.match( '.*PAULO',case=False))]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
2436,2564,Guarulhos - Governador André Franco Montoro In...,Sao Paulo,Brazil,GRU,SBGR,-23.435556,-46.473057,2459,-3,S,America/Sao_Paulo,airport,OurAirports
2464,2593,Campo de Marte Airport,Sao Paulo,Brazil,\N,SBMT,-23.509100,-46.637798,2368,-3,S,America/Sao_Paulo,airport,OurAirports
2486,2618,Congonhas Airport,Sao Paulo,Brazil,CGH,SBSP,-23.626110,-46.656387,2631,-3,S,America/Sao_Paulo,airport,OurAirports
2499,2631,Paulo Afonso Airport,Paulo Alfonso,Brazil,PAV,SBUF,-9.400880,-38.250599,883,-3,S,America/Fortaleza,airport,OurAirports
6046,8256,Senadora Eunice Micheles Airport,Sao Paulo de Olivenca,Brazil,OLC,SDCG,-3.467930,-68.920412,335,-4,S,America/Boa_Vista,airport,OurAirports
6397,8927,Lorenzo Airport,Morro de Sao Paulo,Brazil,\N,SNCL,-13.389444,-38.910000,3,-3,S,America/Fortaleza,airport,OurAirports

In [ ]:
df.loc[(df[3]== 'Brazil')]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
2392,2518,Conceição do Araguaia Airport,Conceicao Do Araguaia,Brazil,CDJ,SBAA,-8.348350,-49.301498,653,-3,S,America/Belem,airport,OurAirports
2393,2519,Campo Délio Jardim de Mattos Airport,Rio De Janeiro,Brazil,\N,SBAF,-22.875099,-43.384701,110,-3,S,America/Sao_Paulo,airport,OurAirports
2394,2520,Amapá Airport,Amapa,Brazil,\N,SBAM,2.077510,-50.858200,45,-3,S,America/Fortaleza,airport,OurAirports
2395,2521,Araraquara Airport,Araracuara,Brazil,AQA,SBAQ,-21.812000,-48.132999,2334,-3,S,America/Sao_Paulo,airport,OurAirports
2396,2522,Santa Maria Airport,Aracaju,Brazil,AJU,SBAR,-10.984000,-37.070301,23,-3,S,America/Fortaleza,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7643,13723,Augusto Severo Airport,Natal,Brazil,\N,SBNT,-5.911420,-35.247700,169,\N,\N,\N,airport,OurAirports
7647,13735,Flores Airport,MANAUS,Brazil,\N,SWFN,-3.072778,-60.021111,203,-4,S,\N,airport,OurAirports
7659,13772,Fazenda Uiapuru Airport,COMODORO,Brazil,\N,SWVJ,-13.663889,-56.002220,1519,-4,S,\N,airport,OurAirports
7670,13830,Fazenda Kajussol Airport,Alta Floresta D'Oeste,Brazil,\N,SJYD,-11.964722,-61.686668,636,-4,S,\N,airport,OurAirports
7672,13881,Costa Marques Airport,COSTA MARQUES,Brazil,CQS,SWCQ,-12.421100,-64.251602,555,-4,S,\N,airport,OurAirports

In [ ]:
#maior numero de aeroportos por cidade
df.groupby(2)[2].count().sort_values(ascending=False)

2
London        9
Columbus      8
San Jose      7
Georgetown    7
Alexandria    6
             ..
Helgoland     1
Helena        1
Heihe         1
Heho          1
Žilina        1
Name: 2, Length: 6955, dtype: int64

In [ ]:
#maior numero de aeroporto por pais
df.groupby(3)[3].count().sort_values(ascending=False)

3
United States              1512
Canada                      430
Australia                   334
Russia                      264
Brazil                      264
                           ...
Cocos (Keeling) Islands       1
Christmas Island              1
Niue                          1
Norfolk Island                1
Grenada                       1
Name: 3, Length: 237, dtype: int64

In [ ]:
df.describe()

                  0            6            7             8
count   7698.000000  7698.000000  7698.000000   7698.000000
mean    5170.950117    25.808442    -1.390546   1015.873344
std     3777.259930    28.404946    86.519162   1628.775132
min        1.000000   -90.000000  -179.876999  -1266.000000
25%     1993.250000     6.907983   -78.974699     63.000000
50%     4068.000000    34.085701     6.375653    352.000000
75%     7728.750000    47.239551    56.000599   1203.000000
max    14110.000000    89.500000   179.951004  14472.000000

In [ ]:
#Considerando o dataset airports.dat, qual aeroporto apresenta a maior altitude? 14472 ft, Daocheng Yading Airport	Daocheng
df.sort_values(8,ascending=False)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
6542,9310,Daocheng Yading Airport,Daocheng,China,DCY,ZUDC,29.323056,100.053333,14472,8,N,Asia/Shanghai,airport,OurAirports
5028,6396,Qamdo Bangda Airport,Bangda,China,BPX,ZUBD,30.553600,97.108299,14219,8,U,Asia/Shanghai,airport,OurAirports
6393,8921,Kangding Airport,Kangding,China,KGT,ZUKD,30.157500,101.734722,14042,8,N,Asia/Shanghai,airport,OurAirports
5872,7932,Ngari Gunsa Airport,Shiquanhe,China,NGQ,ZUAL,32.100000,80.053056,14022,8,N,Asia/Shanghai,airport,OurAirports
2625,2762,El Alto International Airport,La Paz,Bolivia,LPB,SLLP,-16.513300,-68.192299,13355,-4,U,America/La_Paz,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2069,2151,Ramsar Airport,Ramsar,Iran,RZR,OINR,36.909901,50.679600,-70,3.5,E,Asia/Tehran,airport,OurAirports
4087,4357,Atyrau Airport,Atyrau,Kazakhstan,GUW,UATG,47.121899,51.821400,-72,5,U,Asia/Oral,airport,OurAirports
5721,7646,Jacqueline Cochran Regional Airport,Palm Springs,United States,TRM,KTRM,33.626701,-116.160004,-115,-8,A,America/Los_Angeles,airport,OurAirports
1553,1595,Ein Yahav Airfield,Eyn-yahav,Israel,EIY,LLEY,30.621700,35.203300,-164,2,E,Asia/Jerusalem,airport,OurAirports
1558,1600,Bar Yehuda Airfield,Metzada,Israel,MTZ,LLMZ,31.328199,35.388599,-1266,2,E,Asia/Jerusalem,airport,OurAirports

In [ ]:
#Considerando o dataset airports.dat, qual é a média de aeroportos por país?
df.groupby(3)[3].count().mean()

32.48101265822785

In [ ]:
#Considerando o dataset airports.dat, qual é a média de altitude dos aeroportos?
df[8].mean()

1015.873343725643

In [ ]:
df[(df[1]== 'Madang Airport')|(df[0]==2564)|(df[1]=='Goroka Airport') ]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2436,2564,Guarulhos - Governador André Franco Montoro In...,Sao Paulo,Brazil,GRU,SBGR,-23.435556,-46.473057,2459,-3,S,America/Sao_Paulo,airport,OurAirports